version: "3.8"

services:
  constellation:
    build: .
    container_name: constellation
    ports:
      - "8000:8000"
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - SECOND_BRAIN_API=http://second-brain:8001
    depends_on:
      - weaviate
      - second-brain

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true

  second-brain:
    build: ../second-brain
    container_name: second-brain
    ports:
      - "8001:8001"
